# Generated by Django 5.0.1 on 2024-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='secret_key',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='Anonymous', max_length=100, unique=True),
        ),
    ]
